#!/usr/bin/env bash
# compute the total number of incidents per month for each of the months, and then compute the median and median absolute deviation (MAD) across the 12 months



if [[ $# -eq 0 ]]; then
    1>&2 echo "Usage: $0 <file name>"
    exit 1
fi

if [[ ! -s $1 ]]; then
    1>&2 echo "file does not exist or empty:$1"
    exit 1
fi

data=$(cat "$1")
for month in {1..12}; do
    MONTH[$month]=$(echo "$data" | gawk -F '\t' -v mon="$month" '$6 == mon { count++ } END { print count }')
done

IFS=$'\n'
sortmonth=($(sort -n <<<"${MONTH[*]}"))
Sortmonth=${#sortmonth[@]}
if (( Sortmonth % 2 == 1 )); then
    median=${sortmonth[Sortmonth/2]}
else
    median=$(( (sortmonth[Sortmonth/2]+sortmonth[Sortmonth/2-1])/2 ))
fi


for i in "${!sortmonth[@]}"; do
    difference=$(( ${sortmonth[i]} - median ))
    abs_difference[$i]=${difference#-}
done
