#!/bin/bash
# Creating a bash script called preprocess to check the error of the data and create year and month column

if [[ $# -eq 0 ]]; then
    1>&2 echo "Usage: wrong script format: $0 <file name>"
    exit 1
fi

if [[ ! -s $1 ]]; then
    1>&2 echo "Usage: the file is empty or DNE: $1"
    exit 1
fi


echo -e "Name_of_Covered_Entity\tState\tIndividuals_Affected\tDate_of_Breach\tType_of_Breach\tMonth\tYear"

while IFS=$'\t' read Name_of_Covered_Entity State Individuals_Affected Date_of_Breach Type_of_Breach Location; do
    date=$(echo $Date_of_Breach | gawk -F'-' '{print $1}')
    Mon=$(echo $new_date | cut -d'/' -f1)
    Yr=$(echo $new_date | cut -d'/' -f3)
done < $1
